# @package _global_
data:
  znear: 0.2
  zfar: 10
  category: scannet
  white_background: true
  use_neighbor_imgs: true
  use_self_supervise: false
  supervised_max_distance: 5
  pts_dataset_root: /path/to/scannet/dataset
  rgb_dataset_root: /path/to/scannet/color
