defaults:
  - /settings@_here_  # Superimpose the basic settings
  - /dataset/scannet@_here_  # Superimpose the dataset settings

general:
  cuda: true
  device: [0,1,2,3,4,5,6,7]
  random_seed: 0

data:
  fov: 57.9516132895
  training_width: 160
  training_height: 120
  input_images: 8

model:
  backbone_type: ptv3
  in_channels: 3
  aug: false

opt:
  iterations: 20000
  mode: "train"
  # use ScanNet v2 dataset
  level: "scene"
  use_fusion: true
  base_lr: 0.0001
  batch_size: 8
  step_lr: 5000
  lr_gamma: 0.8
  test_generation_num: 1
  loss: l2
  start_lpips_after: 10000
