defaults:
  - /settings@_here_  # Superimpose the basic settings
  - /dataset/scannet@_here_  # Superimpose the dataset settings

general:
  cuda: true
  device: [0,1,2,3]
  random_seed: 42

data:
  fov: 57.9516132895
  training_width: 160
  training_height: 120
  input_images: 8

model:
  backbone_type: sparseunet
  in_channels: 3
  aug: false
  offset_scale: 0.2

opt:
  iterations: 60000
  mode: "train"
  # use ScanNet v2 dataset
  level: "scene"
  use_fusion: true
  base_lr: 0.0001
  batch_size: 4
  test_generation_num: 1
  loss: l2
  step_lr: 10000
  lr_gamma: 0.9
  start_lpips_after: 30000